{
  Table table=new Table();
  Throwable[] causes=new Throwable[]{new RuntimeException("Broken in the first way."),new RuntimeException("Broken in the second way.")};
  CacheUpdateException exception=new CacheUpdateException(table,"Error during Table cache update.",causes);
  Assert.assertSame(causes[0],exception.getCause());
  Assert.assertEquals("Error during Table cache update. Additional causes not shown.",exception.getMessage());
}
