{
  Table table=new Table();
  Throwable[] causes=new Throwable[]{new RuntimeException("Broken in one way.")};
  CacheUpdateException exception=new CacheUpdateException(table,"Error during Table cache update.",causes);
  Assert.assertSame(causes[0],exception.getCause());
  Assert.assertEquals("Error during Table cache update.",exception.getMessage());
}
